// Game types
export const START_GAME_FETCH = "START_GAME_FETCH";
export const START_GAME_SUCCESS = "START_GAME_SUCCESS";
export const START_GAME_ERROR = "START_GAME_ERROR";

export const PLAY_FETCH = "PLAY_FETCH";
export const PLAY_SUCCESS = "PLAY_SUCCESS";
export const PLAY_ERROR = "PLAY_ERROR"

// Config types
export const GET_INITIAL_CONFIG_FETCH = "GET_INITIAL_CONFIG_FETCH";
export const GET_INITIAL_CONFIG_SUCCESS = "GET_INITIAL_CONFIG_SUCCESS";
export const GET_INITIAL_CONFIG_ERROR = "GET_INITIAL_CONFIG_ERROR";
export const SET_CONFIG = "SET_CONFIG";
