// Config types
export const GET_INITIAL_CONFIG_FETCH = "GET_INITIAL_CONFIG_FETCH";
export const GET_INITIAL_CONFIG_SUCCESS = "GET_INITIAL_CONFIG_SUCCESS";
export const GET_INITIAL_CONFIG_ERROR = "GET_INITIAL_CONFIG_ERROR";
export const SET_CONFIG = "SET_CONFIG";
